"""Plain-English explanations for every finding the scanner can produce.
Written by hand so they are always correct; only findings that were really detected are explained."""

EXPLANATIONS = {
    "CERT_EXPIRED": {
        "title": "Certificate has expired",
        "problem": "The site's security certificate is past its expiry date.",
        "why_it_matters": "Browsers show a full-page warning and most visitors will leave.",
        "impact": "Visitors cannot safely confirm they are talking to the real site.",
        "fix": "Renew the certificate now (for Let's Encrypt run 'certbot renew') and set up automatic renewal.",
    },
    "CERT_EXPIRES_VERY_SOON": {
        "title": "Certificate expires within a week",
        "problem": "The certificate will expire in 7 days or less.",
        "why_it_matters": "Once it expires, browsers block the site with a warning.",
        "impact": "The site will look broken or unsafe to every visitor.",
        "fix": "Renew the certificate today and check that automatic renewal is working.",
    },
    "CERT_EXPIRES_SOON": {
        "title": "Certificate expires within 14 days",
        "problem": "The certificate will expire in less than two weeks.",
        "why_it_matters": "Forgotten renewals are one of the most common causes of HTTPS outages.",
        "impact": "If it is not renewed in time, browsers will block the site.",
        "fix": "Renew it now. Automatic renewal normally happens with about 30 days left, so check that it is working.",
    },
    "CERT_HOSTNAME_MISMATCH": {
        "title": "Certificate is for a different domain",
        "problem": "The certificate does not list this domain name.",
        "why_it_matters": "Browsers treat this the same as a possible impersonation and show a warning.",
        "impact": "Visitors see a security error and cannot tell the real site from a fake one.",
        "fix": "Get a certificate that includes this exact domain (and www. if used), then install it on the server.",
    },
    "CERT_SELF_SIGNED": {
        "title": "Certificate is self-signed",
        "problem": "The certificate was created by the server itself, not by a trusted authority.",
        "why_it_matters": "Anyone can make a self-signed certificate, so it proves nothing about who runs the site.",
        "impact": "Browsers show a warning, and attackers could swap in their own certificate unnoticed.",
        "fix": "Replace it with a certificate from a trusted authority. Let's Encrypt provides them for free.",
    },
    "CERT_UNTRUSTED": {
        "title": "Certificate is not trusted",
        "problem": "The certificate was issued by an authority that browsers do not trust, or the chain is incomplete.",
        "why_it_matters": "Browsers cannot confirm the site's identity, so they show a warning.",
        "impact": "Visitors see a security error; some apps and devices refuse to connect at all.",
        "fix": "Use a certificate from a trusted authority and install the full chain (including intermediate certificates).",
    },
    "TLS_1_0_ENABLED": {
        "title": "Outdated TLS 1.0 is enabled",
        "problem": "The server still accepts TLS 1.0, a version from 1999.",
        "why_it_matters": "TLS 1.0 has known weaknesses and all major browsers have dropped it.",
        "impact": "An attacker could force an old, weaker connection and try to read the traffic.",
        "fix": "Turn off TLS 1.0 in the web server settings and allow only TLS 1.2 and 1.3.",
    },
    "TLS_1_1_ENABLED": {
        "title": "Outdated TLS 1.1 is enabled",
        "problem": "The server still accepts TLS 1.1, which is officially deprecated.",
        "why_it_matters": "TLS 1.1 uses old cryptography and is no longer supported by browsers.",
        "impact": "It gives attackers an older, weaker option to aim for.",
        "fix": "Turn off TLS 1.1 in the web server settings and allow only TLS 1.2 and 1.3.",
    },
    "NO_MODERN_TLS": {
        "title": "No modern TLS version",
        "problem": "The server supports neither TLS 1.2 nor TLS 1.3.",
        "why_it_matters": "Modern browsers require at least TLS 1.2.",
        "impact": "Most visitors cannot open the site securely at all.",
        "fix": "Update the web server and its TLS library, then enable TLS 1.2 and TLS 1.3.",
    },
    "TLS_1_3_NOT_SUPPORTED": {
        "title": "TLS 1.3 is not supported",
        "problem": "The server does not offer TLS 1.3, the newest and fastest version.",
        "why_it_matters": "TLS 1.3 removes old, risky options and connects faster.",
        "impact": "Small: TLS 1.2 is still safe, but the site misses the improvements of 1.3.",
        "fix": "Enable TLS 1.3 in the web server settings (supported by recent nginx, Apache and IIS).",
    },
    "WEAK_CIPHERS": {
        "title": "Weak ciphers are accepted",
        "problem": "The server still accepts encryption methods that are known to be breakable.",
        "why_it_matters": "If a weak cipher is used, the encryption may be broken.",
        "impact": "An attacker on the network might read or change the data.",
        "fix": "Remove RC4, 3DES, DES, NULL, anonymous and EXPORT ciphers from the server's cipher list.",
    },
    "NO_FORWARD_SECRECY": {
        "title": "No forward secrecy",
        "problem": "The default connection does not use forward secrecy.",
        "why_it_matters": "Without it, one stolen server key can unlock recordings of old traffic.",
        "impact": "Past conversations could be decrypted if the key ever leaks.",
        "fix": "Prefer ECDHE cipher suites and enable TLS 1.3, which always has forward secrecy.",
    },
    "HSTS_MISSING": {
        "title": "HSTS header is missing",
        "problem": "The site does not tell browsers to always use HTTPS.",
        "why_it_matters": "The first visit can be made over plain HTTP, where it can be intercepted.",
        "impact": "An attacker on public Wi-Fi could redirect visitors to a fake, insecure version.",
        "fix": "Add the header Strict-Transport-Security: max-age=31536000; includeSubDomains",
    },
    "CSP_MISSING": {
        "title": "Content-Security-Policy header is missing",
        "problem": "The site does not limit which scripts a browser may run.",
        "why_it_matters": "It is one of the best defences against injected scripts (XSS).",
        "impact": "An attacker who injects a script into a page has an easier time running it.",
        "fix": "Add a Content-Security-Policy header, starting with a simple policy such as default-src 'self'.",
    },
    "X_FRAME_OPTIONS_MISSING": {
        "title": "X-Frame-Options header is missing",
        "problem": "Other websites are allowed to show this site inside a frame.",
        "why_it_matters": "This enables clickjacking: tricking users into clicking hidden buttons.",
        "impact": "Visitors could be tricked into actions they did not intend.",
        "fix": "Add the header X-Frame-Options: DENY (or SAMEORIGIN if the site frames itself).",
    },
    "X_CONTENT_TYPE_OPTIONS_MISSING": {
        "title": "X-Content-Type-Options header is missing",
        "problem": "Browsers may guess the type of files instead of trusting the server.",
        "why_it_matters": "Guessing can turn an uploaded file into a script that runs.",
        "impact": "Some file-upload attacks become easier.",
        "fix": "Add the header X-Content-Type-Options: nosniff",
    },
    "REFERRER_POLICY_MISSING": {
        "title": "Referrer-Policy header is missing",
        "problem": "The site does not tell browsers how much of the page address to share with other sites.",
        "why_it_matters": "Full page addresses can contain private information.",
        "impact": "Visitors' page addresses may be sent to other websites when they click links.",
        "fix": "Add the header Referrer-Policy: strict-origin-when-cross-origin",
    },
    "CERT_WEAK_KEY": {
        "title": "Certificate key is too short",
        "problem": "The certificate uses a key that is shorter than today's minimum (2048-bit RSA or 224-bit EC).",
        "why_it_matters": "Short keys can be broken with enough computing power.",
        "impact": "An attacker who breaks the key could pretend to be the site.",
        "fix": "Create a new key of at least 2048-bit RSA (or 256-bit EC) and get a new certificate for it.",
    },
    "CERT_WEAK_SIGNATURE": {
        "title": "Certificate uses an outdated signature",
        "problem": "The certificate is signed with SHA-1 or MD5, which are no longer considered safe.",
        "why_it_matters": "Researchers have created fake documents with the same SHA-1/MD5 signature.",
        "impact": "Browsers reject or warn about such certificates, and forgery becomes possible.",
        "fix": "Get a new certificate signed with SHA-256. Every modern certificate authority does this by default.",
    },
    "SSL_2_ENABLED": {
        "title": "Ancient SSL 2.0 is enabled",
        "problem": "The server still accepts SSL 2.0, a protocol from 1995.",
        "why_it_matters": "SSL 2.0 is completely broken and enables the DROWN attack.",
        "impact": "Encrypted traffic, even on newer protocols, may be decrypted by an attacker.",
        "fix": "Turn off SSL 2.0 completely in the web server settings and allow only TLS 1.2 and 1.3.",
    },
    "SSL_3_ENABLED": {
        "title": "Outdated SSL 3.0 is enabled",
        "problem": "The server still accepts SSL 3.0, which was retired in 2015.",
        "why_it_matters": "SSL 3.0 is broken by the POODLE attack.",
        "impact": "An attacker on the network can decrypt parts of the traffic, such as login cookies.",
        "fix": "Turn off SSL 3.0 in the web server settings and allow only TLS 1.2 and 1.3.",
    },
    "HEARTBLEED": {
        "title": "Vulnerable to Heartbleed",
        "problem": "The server runs an OpenSSL version with the Heartbleed bug (CVE-2014-0160).",
        "why_it_matters": "Anyone can read pieces of the server's memory without logging in.",
        "impact": "Private keys, passwords and session cookies can leak to attackers.",
        "fix": "Update OpenSSL immediately, then replace the certificate and its private key and reset user sessions.",
    },
    "CCS_INJECTION": {
        "title": "Vulnerable to OpenSSL CCS injection",
        "problem": "The server's OpenSSL has the CCS injection bug (CVE-2014-0224).",
        "why_it_matters": "An attacker in the middle can force weak keys onto the connection.",
        "impact": "Traffic between visitors and the site could be read or changed.",
        "fix": "Update OpenSSL on the server to a current version and restart the web server.",
    },
    "ROBOT_VULNERABLE": {
        "title": "Vulnerable to the ROBOT attack",
        "problem": "The server's RSA key exchange leaks information (the ROBOT attack).",
        "why_it_matters": "An attacker can use the server to decrypt recorded traffic or sign data with its key.",
        "impact": "Past and present connections that use RSA key exchange may be decrypted.",
        "fix": "Update the server or load balancer software, and disable cipher suites that start with TLS_RSA_.",
    },
    "NO_HTTPS_REDIRECT": {
        "title": "HTTP does not redirect to HTTPS",
        "problem": "Visiting http:// shows the site without encryption instead of sending visitors to https://.",
        "why_it_matters": "People who type the address without https:// stay on an unprotected connection.",
        "impact": "Anyone on the same network can read or change what those visitors see and send.",
        "fix": "Make the server answer every http:// request with a permanent (301) redirect to the same https:// address.",
    },
    "HSTS_SHORT_MAX_AGE": {
        "title": "HSTS lasts too short",
        "problem": "The HSTS header tells browsers to remember HTTPS for less than 6 months.",
        "why_it_matters": "When it runs out, visitors can again be tricked into using plain HTTP.",
        "impact": "Returning visitors are protected for a shorter time than recommended.",
        "fix": "Set Strict-Transport-Security: max-age=31536000; includeSubDomains (one year).",
    },
    "CSP_REPORT_ONLY": {
        "title": "Content-Security-Policy is only in report mode",
        "problem": "The site sends its CSP as Content-Security-Policy-Report-Only, which logs problems but blocks nothing.",
        "why_it_matters": "Report-only mode is meant for testing a policy before switching it on.",
        "impact": "Injected scripts still run; the policy gives no protection yet.",
        "fix": "When the reports look clean, send the same policy as Content-Security-Policy to start enforcing it.",
    },
    "CSP_UNSAFE_DIRECTIVES": {
        "title": "Content-Security-Policy allows unsafe scripts",
        "problem": "The CSP contains 'unsafe-inline' or 'unsafe-eval'.",
        "why_it_matters": "These switch off much of the protection that CSP is meant to give against injected scripts.",
        "impact": "An attacker who injects script code into a page can still get it to run.",
        "fix": "Replace 'unsafe-inline' with nonces or hashes, and remove 'unsafe-eval' by avoiding eval() in the site's code.",
    },
    "COOKIE_NOT_SECURE": {
        "title": "Cookies without the Secure flag",
        "problem": "Some cookies may also be sent over plain, unencrypted HTTP.",
        "why_it_matters": "Cookies often hold login sessions.",
        "impact": "Someone on the same network could steal a session and log in as the visitor.",
        "fix": "Add the Secure attribute to every cookie (Set-Cookie: name=value; Secure; HttpOnly; SameSite=Lax).",
    },
    "COOKIE_NO_HTTPONLY": {
        "title": "Cookies readable by scripts",
        "problem": "Some cookies do not have the HttpOnly flag, so JavaScript on the page can read them.",
        "why_it_matters": "If an attacker injects a script, it can copy these cookies.",
        "impact": "Session cookies could be stolen through an XSS bug. (Cookies that the site's own scripts need may be fine.)",
        "fix": "Add the HttpOnly attribute to every cookie that scripts do not need, especially session cookies.",
    },
    "COOKIE_NO_SAMESITE": {
        "title": "Cookies without SameSite",
        "problem": "Some cookies do not say whether other websites may send them along.",
        "why_it_matters": "SameSite is a simple defence against cross-site request forgery (CSRF).",
        "impact": "Another website could make a visitor's browser perform actions on this site.",
        "fix": "Add SameSite=Lax (or Strict) to cookies.",
    },
    "CAA_MISSING": {
        "title": "No CAA record",
        "problem": "The domain's DNS does not say which certificate authorities may issue certificates for it.",
        "why_it_matters": "Without CAA, any of the hundreds of trusted authorities could be tricked into issuing a certificate for your domain.",
        "impact": "Small on its own, but CAA is a cheap extra layer against fake certificates.",
        "fix": "Add a CAA DNS record for your certificate provider, e.g. example.com. CAA 0 issue \"letsencrypt.org\".",
    },
    "CERT_CHAIN_INCOMPLETE": {
        "title": "Certificate chain is incomplete",
        "problem": "The server sends its own certificate but not the intermediate certificate that links it to a trusted authority.",
        "why_it_matters": "Chrome, Edge and Safari download the missing piece themselves, but Firefox, mobile apps, command-line tools and older devices do not.",
        "impact": "Some visitors and apps get a security error even though the certificate itself is fine.",
        "fix": "Install the full chain on the server: your certificate followed by the intermediate certificate(s) from your certificate provider (often a file named fullchain.pem).",
    },
    "VARIANT_CERT_CHAIN_INCOMPLETE": {
        "title": "The other address has an incomplete certificate chain",
        "problem": "The www (or non-www) address does not send its intermediate certificate.",
        "why_it_matters": "Chrome fixes this by itself, but Firefox, apps and older devices show an error for that address.",
        "impact": "Some visitors who type that version of the address see a security warning.",
        "fix": "Install the full chain (fullchain.pem) for that address too.",
    },
    "VARIANT_NO_HTTPS": {
        "title": "The other address does not use HTTPS",
        "problem": "The www (or non-www) version of the address exists but does not serve HTTPS.",
        "why_it_matters": "Many visitors type the address with or without www.",
        "impact": "Those visitors get an error or an unprotected page.",
        "fix": "Serve HTTPS on both names with one certificate that includes both, then redirect one to the other.",
    },
    "VARIANT_CERT_INVALID": {
        "title": "The other address has a bad certificate",
        "problem": "The www (or non-www) version of the address shows a certificate that browsers reject.",
        "why_it_matters": "Visitors who use that version see a full-page security warning.",
        "impact": "The site looks broken or unsafe to part of your visitors.",
        "fix": "Get a certificate that covers both names (for example example.com and www.example.com).",
    },
    "VARIANT_NO_HTTPS_REDIRECT": {
        "title": "The other address does not redirect to HTTPS",
        "problem": "The http:// version of the www (or non-www) address does not send visitors to https://.",
        "why_it_matters": "People who type that version stay on an unprotected connection.",
        "impact": "Anyone on the same network could read or change what those visitors see.",
        "fix": "Redirect http:// on both names with a permanent (301) redirect to your main https:// address.",
    },
}


def explain_findings(findings: list[dict]) -> dict:
    return {f["id"]: EXPLANATIONS[f["id"]] for f in findings if f["id"] in EXPLANATIONS}
